### ISSUE TITLE
Site needs to be Secure

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#193]
As a product owner
I would like my site to be sufficiently secure
So that data cannot be obtained by attackers

I propose that we use SSL via https://letsencrypt.org/about/

https://github.com/dwyl/learn-heroku/blob/master/SSL-certificate-step-by-step-setup-instructions.md

Waiting on confirmation by @ajburls for security requirements for the application - once you have these Amanda, please update this issue and add a priority label, for now I will assume it is a 2 and is essential for this sprint (luckily we still have some extra time in the scope).

**Comment by ajburls** [comment]
Ok

**Comment by SimonLab** [comment]
@markwilliamfirth I've configure the application to automatically redirect to https. Could you try on your side and see if it's working, thanks

**Comment by markwilliamfirth** [comment]
<img width="393" alt="screen shot 2017-09-05 at 12 18 32" src="https://user-images.githubusercontent.com/5732209/30056783-5ca315d6-9234-11e7-8333-edff27c9a185.png">
<img width="1246" alt="screen shot 2017-09-05 at 12 18 25" src="https://user-images.githubusercontent.com/5732209/30056784-5cbf13f8-9234-11e7-92c1-7925929180f2.png">

@SimonLab it still shows as this^

**Comment by SimonLab** [comment]
I think on the other url (the staging one) the application is automatically redirected to https. So it might be an issue linked to the configuration of the domain name?

**Comment by markwilliamfirth** [comment]
@SimonLab now when i go to bestevidence.info it redirects to https://best-evidence-app.herokuapp.com/ but we don't want it to redirect, we want the domain to stay in the search bar - is that still possible?

**Comment by SimonLab** [comment]
![image](https://user-images.githubusercontent.com/6057298/30059744-4e0f653e-9238-11e7-9aed-ac6b9cd13dfe.png)

I've updated the url in the config. However the https is not find, is this a domain name config problem @markwilliamfirth ?

**Comment by markwilliamfirth** [comment]
<img width="986" alt="screen shot 2017-09-05 at 13 48 38" src="https://user-images.githubusercontent.com/5732209/30059807-f48f952a-9240-11e7-9c50-f3d7d2d210e3.png">

@SimonLab this is the domain config

I was under the impression https only works for domains with ssl certificates

**Comment by markwilliamfirth** [comment]
@SimonLab 

>SSL Endpoint is only useful for custom domains. All default appname.herokuapp.com domains are already SSL-enabled and can be accessed by using https, for example, https://appname.herokuapp.com.

https://devcenter.heroku.com/articles/ssl-endpoint

**Comment by SimonLab** [comment]
could you try to update the config to use https in the url? If the url is just a redirection to the heroku app I'm not sure why it couldn't redirect to the https of the heroku application. But I let you check with ssl if you want to try, let me know

**Comment by markwilliamfirth** [comment]
@SimonLab my understanding is that:

- Heroku links (https://appname.herokuapp.com) are already secure
- Amanda wants a secure custom domain name to link to the app
- The custom domain we have is not currently secure
- In order to make it secure we need an ssl certificate for the custom domain

Is this correct?

@nelsonic @iteles we could benefit from some of your security expertise here if by chance you see this

**Comment by markwilliamfirth** [comment]
@SimonLab I just added a paid dyno and configured ssl on heroku

this came up:

<img width="588" alt="screen shot 2017-09-05 at 14 08 23" src="https://user-images.githubusercontent.com/5732209/30060484-d6d8053c-9243-11e7-8f9c-d4cb5df750ef.png">

**Comment by SimonLab** [comment]
@markwilliamfirth I'm not sure about the process to configure ssl with heroku but we should find some info here: https://devcenter.heroku.com/articles/ssl-endpoint . The cutom domain name doesn't yet redirect to the app so it either take a bit of time to reset or we are missing something in the configuration

**Comment by markwilliamfirth** [comment]
@SimonLab site still appears as insecure

**Comment by iteles** [comment]
@markwilliamfirth That's correct, if we want `https` on a custom domain, we'll need an SSL certificate configured for it.

@SimonLab Have you looked at elements.heroku.com/addons/expeditedssl ?
Two options here:
+ Use letsencrypt as  per the description of this issue (I can see this hasn't been done yet because your settings dash doesn't match https://github.com/dwyl/learn-heroku/blob/master/SSL-certificate-step-by-step-setup-instructions.md#step-77-confirm-the-certificate-was-added)
+ Or the **simpler** option is  to use expeditedSSL which is budgeted for for 6 months 👍 
  + See [this issue](https://github.com/cul-2016/quiz/issues/374#issuecomment-282020988) for some more info on that and who to speak to for troubleshooting

**Comment by SimonLab** [comment]
@markwilliamfirth could you test again to access the production website, I think this should be resolved now

**Comment by markwilliamfirth** [comment]
<img width="633" alt="screen shot 2017-09-07 at 08 53 39" src="https://user-images.githubusercontent.com/5732209/30152143-17866620-93aa-11e7-8e1f-6a3e555057d3.png">

**Comment by SimonLab** [comment]
It's working on my side:
![image](https://user-images.githubusercontent.com/6057298/30154283-58c9f74e-93b1-11e7-81b0-e2471ce61580.png)

could you try to refresh the page and to make sure you don't use any cached version, maybe try on incognito mode

**Comment by markwilliamfirth** [comment]
Still doesn't work for me - on Chrome incognito or Safari (no history on safari)

**Comment by ajburls** [comment]
Nor me on Android, iPhone or computer

**Comment by SimonLab** [comment]
I thinks it's working if you try with the www: ```www.bestevidence.info```
@markwilliamfirth you have define the configuration like this on Heroku:
![image](https://user-images.githubusercontent.com/6057298/30154673-8b2264be-93b2-11e7-9353-df6fc2fea94c.png)
You could try to remove the ```www``` and test that on the dns config

**Comment by ajburls** [comment]
No, this redirects to https://bestevidence.info and is still not working

**Comment by markwilliamfirth** [comment]
@SimonLab yes this works: https://www.bestevidence.info/

Good spot - there is no root domain on Heroku (https://github.com/dwyl/dwyl-site/issues/210#issuecomment-304054487)

@ajburls please try: https://www.bestevidence.info/

If it redirects due to history, please edit in the URL bar and enter again

**Comment by iteles** [comment]
@markwilliamfirth A note that github just erased the `www` from your URL.

To be clear `https://www.bestevidence.info` functions as expected.

`https://bestevidence.info` does not exist.

**Comment by ajburls** [comment]
Ok. This working on Android. I have no battery life left in iPhone. I will close this now on assumption it will work. Thanks

**Comment by ajburls** [comment]
Ok. This working on Android. I have no battery life left in iPhone. I will close this now on assumption it will work. Thanks
